spring:
  application:
    name: "configserver"
  profiles:
#    active: native
     active: git

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

  cloud:
    config:
      server:
        git:
          uri : "https://github.com/sharooque7/configserver.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///Users//sharooque//Documents//Microservices//Udemy//config"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "1234444"

server:
  port: 8071

logging:
  level:
    com:
      ainzson:
        configserver: DEBUG

